version: 2.1

orbs:
  docker: circleci/docker@2.1.0

jobs:
  build-and-push-docker-image:
    executor: docker/docker
    resource_class: medium
    steps:
      # Hapi 1: Merr kodin
      - checkout

      # Hapi 2: NDEZ MOTORIN E DOCKER-IT (Ky është hapi që mungonte)
      - docker/setup_remote_docker

      # Hapi 3: Bën login në Docker Hub
      - docker/check

      # Hapi 4: Ndërton imazhin
      - docker/build:
          image: '${DOCKER_LOGIN}/hellonodejs'
          tag: 'latest'

      # Hapi 5: Ngarkon imazhin
      - docker/push:
          image: '${DOCKER_LOGIN}/hellonodejs'
          tag: 'latest'

workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push-docker-image