version: 2.1

orbs:
  docker: circleci/docker@2.1.0

jobs:
  build-and-push-docker-image:
    executor: docker/docker
    resource_class: medium
    steps:
      # Hapi 1: Merr kodin nga depoja
      - checkout

      # Hapi 2: Bën login në Docker Hub duke përdorur variablat e mjedisit
      # KUJDES: Sigurohu që variablat në CircleCI quhen DOCKER_LOGIN dhe DOCKER_PASSWORD
      - docker/check

      # Hapi 3: Ndërton imazhin Docker
      - docker/build:
          image: '${DOCKER_LOGIN}/hellonodejs'
          tag: 'latest'

      # Hapi 4: Ngarkon imazhin në Docker Hub
      - docker/push:
          image: '${DOCKER_LOGIN}/hellonodejs'
          tag: 'latest'

workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push-docker-image