version: 2.1

# Orbs sind wiederverwendbare Pakete, die komplexe Aufgaben vereinfachen
orbs:
  docker: circleci/docker@2.1.0

# Workflows definieren die Abfolge von Jobs
workflows:
  build_and_push_image:
    jobs:
      - docker/publish:
          # Definiert den Namen und den Tag für das Docker-Image
          resource_class: medium
          image: '${DOCKERHUB_USERNAME}/hellonodejs'
          tag: 'latest'