version: 2.1

orbs:
  docker: circleci/docker@2.1.0

jobs:
  build-and-push-docker-image:
    # Ky executor përgatit automatikisht një mjedis me Docker të instaluar
    executor: docker/docker
    resource_class: medium
    steps:
      # Hapi 1: Merr kodin
      - checkout

      # Hapi 2: Bën login në Docker Hub (HAPI I RËNDËSISHËM QË MUNGONTE)
      # Kjo komandë përdor variablat e mjedisit DOCKERHUB_USERNAME dhe DOCKERHUB_TOKEN
      - docker/check

      # Hapi 3: Ndërton dhe ngarkon imazhin
      - docker/build-and-push:
          image: '${DOCKERHUB_USERNAME}/hellonodejs'
          tag: 'latest'

workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push-docker-image